### PR TITLE
feature/improve-styling

### PR DESCRIPTION
**Pull request by pt1602**
Hey, 

I added an minimalistic dark mode by changing the background based on the user prefered color scheme.

Further I refactored the code a little bit an compromised the images.

### CODE REVIEW

**Comment by ManishMadan2882** [comment]
Can you deploy it on pages or show some screenshots?

**Comment by pt1602** [comment]
You can simply checkout my branch and view the changes.

**Comment by ManishMadan2882** [comment]
@pt1602 your branch has conflicts

**Comment by ManishMadan2882** [comment]
You need to fix those conflicts so that we can proceed

**Comment by pt1602** [comment]
Sure it has, because you merged some else's dark mode in the meantime.

**Pull request closed without merging**
